name: meteorify
description: |
  A Dart package to interact with Meteor.js
  Connect your flutter apps, written in Dart, to the Meteor framework using DDP.
version: 1.0.4
homepage: https://github.com/martintadashi/meteorify
repository: https://github.com/martintadashi/meteorify
author: Shivam Arora <email.shivamarora@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ddp: ^0.0.13
  crypto: ^2.1.3
  shared_preferences: ^0.5.3
  rxdart: ^0.22.2
  logger:
  json_annotation: ^3.0.0
  path: ^1.6.4
  path_provider: ^1.1.2
  mongo_dart: ^0.3.6


dev_dependencies:
  flutter_test:
    sdk: flutter